import { Component } from '@angular/core';

@Component({
  selector: 'app-user-list',
  templateUrl: './user-list.component.html',
  styleUrls: ['./user-list.component.scss']
})
export class UserListComponent {
  public tableHeaders: string[] = ['Username','First name','Last name','Email','Type'];
  public users = [
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    },
    {
      username:'mperry1992',
      first_name:'Matthew',
      last_name:'Perry',
      email:'matthew@mail.com',
      user_type:'Administrator'
    }
    ]
}
